SciCatProject/frontend

src/app/shared/pipes/filesize.pipe.spec.ts
src/app/shared/pipes/filesize.pipe.ts

Removing extra decimal places in data tables
Data table looks cluttered, only rough estimate of filesize is necessary
* Items added
* changes made

remove decimal places in filesize

---

src/app/app-config.module.ts
src/app/datasets/datafiles/datafiles.component.css
src/app/datasets/datafiles/datafiles.component.html
src/app/datasets/datafiles/datafiles.component.ts
src/environments/environment.ts

Adds checkboxes to the datafile listing, plus a [Download] button that sends the user to a configurable external target where the file download can be completed.
Enable by adding the following to your environment file:
multipleDownloadEnabled: true,
multipleDownloadAction: "http://0.0.0.0:9999/whatever"
Upon clicking "Download", it sends a POST request to the external service where the data has the following format:
{
"base": "/data/group-2/4",
"files": ["datafile_0.h5", "datafile_2.h5", "datafile_3.h5"]
}

Implemented optional, configurable multiple download

---

src/app/datasets/dashboard/dashboard.component.html

Reintroduces the tiny gap between the sidebar and the dataset table that was lost at some point.

Reintroduces margin between sidebar and dataset table

---

package.json
src/app/policies/archive-settings/archive-settings.component.html
src/app/policies/archive-settings/archive-settings.component.scss

Add float right to archive setting button group
Firefox was not respecting align=right to changed to css float right
* Items added
* changes made

specify rightalign in archive settings

---

src/app/datasets/datasets-filter/datasets-filter.component.html
src/app/datasets/datasets-filter/datasets-filter.component.ts

- Preventing form submit when pressing enter in the 'Text search'.
- For' Location', 'Group', 'Type' and 'Keywords' filters:
- - Show all suggestions when first selecting the (empty) field
- - When typing text, show only suggestions that match (contains) the typed text.
- - When pressing enter, automatically add the first (top) suggestion.
- - When adding a suggestion, clear the corresponding text field
- - After having added a suggestion, exclude this from future suggestions.

Dataset filters

---

src/app/datasets/datafiles/datafiles.component.ts

The list of files no longer show up when multipledownload is enabled and has an action. This was caused by a call to getSelectedFiles() from the template prior to dataSource being initialized. 
I added a null check.

prevent error when multipledownload is enabled

---

src/app/state-management/selectors/datasets.selectors.ts

forgot to exclude modeFilter from fullFacet query. Maybe there is a better way.
datasets count/ fullFacet query

do not add modeFilter to facetQuery params

---

src/app/datasets/dataset-detail/dataset-detail.component.html
src/app/datasets/dataset-detail/dataset-detail.component.ts
src/app/state-management/selectors/datasets.selectors.ts

ShowMetaslow
use new selector to fix rendering performance issue caused by large file lists.
There is still the issue of making an API request for currentDataset, and this being slow because its returning a 2GB JSON object with billions of file names in it
slow to render for large data file lists (orig data blocks)

remove origDataBlocks from show metadata

---

src/app/logbooks/logbooks-detail/logbooks-detail.component.ts

Added route params subscription to logbook details, so now it can be accessed from logbooks table again, as well as from the dataset detail view.
Previous update broke access to logbook details from logbooks table.
* Added route params subscription to logbook details

Logbook details can be accessed from Logbooks table again

---

src/app/datasets/dataset-table/dataset-table.component.html

Removed the 'showFirstLastButtons' property from the Dataset table paginator
Skipping breaks backend for large amounts of Datasets
* Removed 'showFirstLastButtons' from mat-paginator

Removed property `showFirstLastButtons` from paginator

---

src/app/datasets/dataset-table/dataset-table.component.html

Adds skip buttons to datasets table
Previously removed due to causing crashes in catamel when handling large amounts of datasets, should now be working.
* Added property 'showFirstLastButtons' to datasets table

Added showFirstLastButtons property to dataset table paginator

---

src/app/datasets/dataset-detail/dataset-detail.component.html
src/app/datasets/dataset-detail/dataset-detail.component.ts

Changed keyword array into clickable chips, linking to filtered datasets table
See issue #445
* Fixes #445
* Changed keyword array into material chip list
* Clicking on a chip updates datasets filter and navigates to datasets table view

Changed keywords to clickable chips

---

src/app/_layout/app-header/app-header.component.html
src/app/_layout/app-header/app-header.component.scss
src/app/_layout/app-header/app-header.component.spec.ts
src/app/_layout/login-header/login-header.component.html
src/app/_layout/login-header/login-header.component.scss

Removes all text except title from header when viewing on small screen
SciCat should be responisve
* Added class to tags containing text and set class to not be displayed on small screens

Made app header responsive

---

src/app/proposals/proposal-dashboard/proposal-dashboard.component.html
src/app/proposals/proposal-dashboard/proposal-dashboard.component.spec.ts
src/app/proposals/proposal-dashboard/proposal-dashboard.component.ts
src/app/shared/modules/table/table.component.html
src/app/shared/modules/table/table.component.scss
src/app/shared/modules/table/table.component.spec.ts
src/app/shared/modules/table/table.component.ts
src/app/shared/modules/table/table.module.ts

Added optional select column to table component
Make table component more versatile
* Added optional select column to table component, toggled by providing boolean property 'select'
* Added output property 'selectAll' to table component, which emits a MatCheckboxChange event when selecting/deselecting all rows
* Added output property 'selectOne' to table component, which emits a CheckboxEvent when selecting/deselecting a row

Added optional select column to table component

---

src/app/datasets/dataset-table/dataset-table.component.scss
src/app/logbooks/logbooks-table/logbooks-table.component.scss

Replaced scss `/deep/` with `::ng-deep`
`/deep/` has been marked as deprecated due to angular-cli switching from node-sass to dart-sass as of angular 8
* Replaced `/deep/` with `::ng-deep` in dataset table component
* Replaced `/deep/` with `::ng-deep` in logbooks table component

Replaced /deep/ with ::ng-deep

---

src/app/proposals/proposal-dashboard/proposal-dashboard.component.spec.ts
src/app/proposals/proposal-dashboard/proposal-dashboard.component.ts

Fixed issue with broken proposal links for proposals with ids containing forward slashes
Navigation broken for proposal ids containing forward slashes
* Added encodeURIComponent to onRowClick

Added encodeURIComponent to #onRowClick()

---

src/app/samples/sample-detail/sample-detail.component.html
src/app/samples/sample-detail/sample-detail.component.scss
src/app/samples/sample-detail/sample-detail.component.spec.ts
src/app/samples/sample-detail/sample-detail.component.ts
src/app/samples/samples.module.ts
src/app/state-management/actions/samples.actions.spec.ts
src/app/state-management/actions/samples.actions.ts
src/app/state-management/effects/samples.effects.spec.ts
src/app/state-management/effects/samples.effects.ts
src/app/state-management/reducers/samples.reducer.spec.ts
src/app/state-management/reducers/samples.reducer.ts
src/app/state-management/selectors/samples.selectors.spec.ts
src/app/state-management/selectors/samples.selectors.ts
src/app/state-management/state/samples.store.ts

Moved sample datasets from list to table in separate tab
Consistent UI
* Added datasetFilters and datasetsCount properties to store
* Added actions for fetching dataset counts and table pagination
* Added effect for fetching datasets count
* Added reducers for new actions
* Added selector for datasets querying
* Added new tab containing shared table to sample details component

Moved sample datasets to table in separate tab

---

package-lock.json
package.json
src/app/app.module.ts
src/app/users/user-settings/user-settings.component.spec.ts

removing unused datetime picker
we are using sattimepicker and not ngui so the import is unneeded
* Items added
* changes made

remove unused datetime picker

---

src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.html
src/app/state-management/effects/datasets.effects.ts
src/app/state-management/reducers/datasets.reducer.ts

firstly, PIDs are not correctly encoded before making api calls.
secondly, the complete reducer is called twice, adding the entity to state twice
thirdly, remove does not remove the item from state or change detection is not functioning correctly

dataset attachments not working correctly for multiple reasons

---

src/app/samples/sample-detail/sample-detail.component.html
src/app/samples/sample-detail/sample-detail.component.scss
src/app/samples/sample-detail/sample-detail.component.spec.ts
src/app/samples/sample-detail/sample-detail.component.ts
src/app/state-management/effects/samples.effects.spec.ts
src/app/state-management/effects/samples.effects.ts
src/app/state-management/reducers/samples.reducer.ts

Added functionality for adding attachments to samples
Requested
* Added shared file uploader to new tab in sample details
* Added attachment viewer to sample details tab
* Updated fetchSample$ effect to include attachments relation
* Added filter to attachments for addAttachmentCompleteAction in samples reducer

Added functionality for adding attachments to samples

---

src/app/jobs/jobs-dashboard/jobs-dashboard.component.spec.ts
src/app/jobs/jobs-dashboard/jobs-dashboard.component.ts
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.spec.ts
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.ts
src/app/logbooks/logbooks-table/logbooks-table.component.spec.ts
src/app/logbooks/logbooks-table/logbooks-table.component.ts
src/app/policies/policies-dashboard/policies-dashboard.component.html
src/app/policies/policies-dashboard/policies-dashboard.component.spec.ts
src/app/policies/policies-dashboard/policies-dashboard.component.ts
src/app/policies/policies.module.ts
src/app/proposals/proposal-dashboard/proposal-dashboard.component.spec.ts
src/app/proposals/proposal-dashboard/proposal-dashboard.component.ts
src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.spec.ts
src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts
src/app/samples/sample-dashboard/sample-dashboard.component.spec.ts
src/app/samples/sample-dashboard/sample-dashboard.component.ts

Added router state to all dashboard components
Requested
* Added filter subscriptions that writes rison encoded filters to url for all dashboard components
* Removed obsolete rootReducer from the changed components spec files

Added router state to all dashboard components

---

src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.spec.ts
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.ts
src/app/shared/MockStubs.ts

Fixed so that logbook router state no longer overrides and redirects from current path
Bug fix
* Added url path condition to logbook router state

Added url path condition to logbook router state

---

src/app/logbooks/logbooks-table/logbooks-table.component.html
src/app/logbooks/logbooks-table/logbooks-table.component.ts
src/app/state-management/reducers/logbooks.reducer.spec.ts
src/app/state-management/reducers/logbooks.reducer.ts

Minor changes in logbooks table and logbooks reducer
Make logbooks from new server visible in scicat
* Added check in the formatImageUrls method in logbooks reducer
* Images now show up in logbooks table

Updated logbooks table to show images

---

CI/ESS/Dockerfile
CI/ESS/Dockerfile.dmscdev
CI/ESS/Dockerfile.dmscprod
CI/ESS/Dockerfile.e2e
CI/ESS/Dockerfile.hub
CI/ESS/copyimages.sh
angular.json

Removed `copyimages.sh` and replaced with `angular.json` `fileReplacements`.
Requested
* Removed `CI/ESS/copyimages.sh`
* Removed `RUN ./CI/ESS/copyimages.sh` from Dockerfiles
* Added images in `CI/ESS/` to `angular.json` `fileReplacements` property

Removed copyimages and replaced with angular fileReplacements

---

src/app/state-management/reducers/logbooks.reducer.spec.ts
src/app/state-management/reducers/logbooks.reducer.ts

Fixes logbook filtering bug created when pagination was added.
Bug fix
* Added `filters.skip: 0` to logbook filtering reducers

Set skip to 0 when applying a new filter

---

src/app/state-management/actions/datasets.actions.spec.ts
src/app/state-management/actions/datasets.actions.ts
src/app/state-management/actions/jobs.actions.spec.ts
src/app/state-management/actions/jobs.actions.ts
src/app/state-management/effects/datasets.effects.spec.ts
src/app/state-management/effects/datasets.effects.ts
src/app/state-management/effects/jobs.effects.spec.ts
src/app/state-management/effects/jobs.effects.ts
src/app/state-management/effects/user.effects.spec.ts
src/app/state-management/effects/user.effects.ts
src/app/state-management/reducers/datasets.reducer.spec.ts
src/app/state-management/reducers/datasets.reducer.ts
src/app/state-management/reducers/jobs.reducer.spec.ts
src/app/state-management/reducers/jobs.reducer.ts

Added datasets limit and jobs limit to the persisted user settings.
Requested.
* Added actions `setDatasetsLimitFilterAction` and `setJobsLimitFilterAction`
* Added user effect `setLimitFilters$` that triggers the two actions above after fetching user settings from catamel
* Added effects `updateUserDatasetsLimit$` and `updateUserJobsLimit$` that triggers `updateUserSettingsAction` and persists changes to catamel

Added actions and effects to persist user settings to backend

---

src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.spec.ts
src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
src/app/samples/sample-detail/sample-detail.component.spec.ts
src/app/samples/sample-detail/sample-detail.component.ts
src/app/shared/modules/file-uploader/file-uploader.component.html
src/app/shared/sdk/models/Attachment.ts
src/app/shared/sdk/services/custom/Attachment.ts
src/app/state-management/reducers/proposals.reducer.spec.ts

Updated sdk and file uploader to comlply with catamel updated of attachment model. Also extended file upoader to allow upload of pdf files.
Required after merging catamel pr [#277](https://github.com/SciCatProject/catamel/pull/277)
* Updated sdk with new changes to Attachment model in catamel
* Updated file uploader to allow pdf files
* Updated file upload logic in sample details and dataset details dashboard to comply with Attachment model changes

Updated sdk + file uploader

---

src/app/samples/sample-dialog/sample-dialog.component.html
src/app/samples/sample-dialog/sample-dialog.component.ts

Added a simple `[disabled]="!form.valid"` to disable the Save button when trying to submit a new Sample.
I've removed the `Validators.required` from `sampleCharacteristics` because its not required. An empty field is already handled by the logic.
Previously the client did not checked, if the form that is submitted is valid, which eventually were caught by loopback's validation without users knowledge.
* Disallowing invalid form for creating new samples
* Save button is only enabled when the form is valid

Disallowing invalid form for creating new samples

---

angular.json
src/app/app.module.ts
src/app/build-specifics/index.prod.ts
src/app/build-specifics/index.ts

Remove store devtools for prod. Should help to cope with problems when browser is running out of memory.
#643 (partly ?)

Remove store devtools for prod

---

src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
src/app/state-management/selectors/datasets.selectors.spec.ts
src/app/state-management/selectors/datasets.selectors.ts

Avoid display of large file arrays in JSON metadata display
Stabilize browser by avoiding display of large of large filearrays i
* in additon to origdatablocks the datablocks information is removed as well

Also datablock file infos needs be removed from JSON display

---

src/app/app-routing/app-routing.module.ts
src/app/app-routing/datasets.guard.ts

Add redirect guard for datasets that redirects an unauthenticated user to the anonymous version of the datasets view.
A user should be able to share links to public datasets with users that don't have a scicat account.
* Add Datasets guard
* Implement Datasets guard for `/datasets` endpoints

Add datasets guard for redirect to anonymous view

---

src/app/shared/modules/scientific-metadata-tree/base-classes/metadata-input-base.spec.ts
src/app/shared/modules/scientific-metadata-tree/base-classes/tree-base.ts
src/app/shared/modules/scientific-metadata-tree/metadata-input/metadata-input.component.spec.ts
src/app/shared/modules/scientific-metadata-tree/metadata-input/metadata-input.component.ts
src/app/shared/modules/scientific-metadata-tree/scientific-metadata-tree.modules.ts
src/app/shared/modules/scientific-metadata-tree/tree-view/tree-view.component.spec.ts
src/app/shared/pipes/format-number.pipe.spect.ts
src/app/shared/pipes/format-number.pipe.ts
src/app/shared/pipes/pipes.module.ts
src/app/shared/services/units.service.ts

Added a new pipe to format large or very small number to exponential number. 
Large or very small number looks better in exponential format than in native format. For example 28e5 vs 2800000 or 28e-5 vs 0.00028
* Items added
- FormatNumberPipe
- new unit and unit symbol s^-1

Add Format number pipe

---

src/app/users/adauth.service.ts

Add rxjs timeout operator to msad login to reduce timeout.
See #579
* Fixes #579
* Add pipe with timeout operator set to 3 s to http request in ADAuthService

Add 3s timeout to ad login

---

src/app/state-management/actions/user.actions.spec.ts
src/app/state-management/actions/user.actions.ts
src/app/state-management/effects/user.effects.spec.ts
src/app/state-management/effects/user.effects.ts
src/app/state-management/reducers/user.reducer.spec.ts

See issue #470 
See issue #470 
- Added an extra error message for failed login due to connection error in AD. This message could be useful when AD server is down or the URL to AD is wrong.
- Drawback : This message is only correct for external users. For functional account that don't require AD authentication the user should know that failed login has to do with invalid username/pwd and not connection error to AD.

Add connection error message

---

cypress.json
cypress/fixtures/rawDataset.json
src/app/app-routing/app-routing.module.ts
src/app/datasets/anonymous-details-dashboard/anonymous-details-dashboard.component.html
src/app/datasets/anonymous-details-dashboard/anonymous-details-dashboard.component.ts
src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.html
src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
src/app/shared/modules/error-page/error-page.component.html
src/app/shared/modules/error-page/error-page.component.scss
src/app/shared/modules/error-page/error-page.component.spec.ts
src/app/shared/modules/error-page/error-page.component.ts
src/app/shared/pipes/json-head.pipe.ts

This PR solves issue #762 and made some small changes to the ErrorPageComponent.
See issue #762 
- View a private dataset without logging in.
- View public dataset while being logged in => return dataset details (was empty before)
- View private dataset that the user doesn't have access to.
- Invalid url redirects to /404

Dataset detail

---

Dockerfile

In order to have one docker image for all the environments, current
dockerfile uses the env variable only during run time
Old version of Dockerfile was such that it required one build per environment. In this way, one image can be built for all the environments and the environment can be selected at run time.
The current Dockerfile is making use of [docker-entrypoint.d](https://github.com/nginxinc/docker-nginx/blob/464886ab21ebe4b036ceb36d7557bf491f6d9320/mainline/alpine/docker-entrypoint.sh) directory parsed by nginx docker-entrypoint.sh at run time.

Modified dockerfile to accept env during run

---

src/app/app-config.module.ts
src/app/publisheddata/publisheddata-details/publisheddata-details.component.html
src/app/publisheddata/publisheddata-details/publisheddata-details.component.spec.ts

Fixes #777  
When working on creating settings in app-config.module.ts in a feature PR, I found I copied the setting for `editPublishedData` and found that the value was always true.
The way these settings are written, it appears that they are intended to have a default. However, the way `editPublishedData` is written, the value can never be false, since `false || true == true`
Additionally, it appears that most projects are using the `lbBaseURL`, but it is not defiend in `AppConfig`. So, for consistency, I added this field.
Fix it so that the code that uses editPublishedData can set to false if wanted.
- added `lbBaseURL` to `AppConfig`
- fixed config logic so that `editPublishedData` can be set to false if configured
I added tests to the place that `editPublishedData` is used, to test …

fix logic in appCofnig

---

CI/PSI/Dockerfile

Restore old Dockerfile and move to CI/PSI/
To restore the current way of deployment to a working version, the old Dockerfile is added for now to CI/PSI and used during build (at PSI)

Add PSI Dockerfile to enable current deployment

---

src/app/app-config.module.ts
src/app/datasets/archiving.service.spec.ts
src/app/datasets/archiving.service.ts
src/app/datasets/batch-view/batch-view.component.ts
src/app/datasets/dataset-table-actions/dataset-table-actions.component.ts
src/app/shared/modules/dialog/dialog.component.html
src/app/shared/modules/dialog/dialog.component.scss
src/app/shared/modules/dialog/dialog.module.ts
src/environments/environment.development.ts
src/environments/environment.prod.ts
src/environments/environment.qa.ts
src/environments/environment.ts

Enable option to choose between different retrieve destinations. If specified, enable the selection of the path on the retrieve location. 
The option can be set by adding the `retrieveDestinations` option to the environment.ts file This is optional, and there is no need to add an empty list in case of no use. E.g.:
```
retrieveDestinations: [{option: "PSI", location: "/home/out"}, {option:"CSCS (Testphase)"}]
```
Expected behaviour when enabling `retrieveDestinations`: 
* The user selects the option from a dropdown list, if the `location` field is non-empty for the selected option, a new field is shown, where she can select the location path, relative to the one in the `retrieveDestinations[i].location`.
* if no `location`, no further field will be shown
* two new fields are added in the …

Retrieve dest

---

src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.scss

As a user, when I view the dataset's details, it would be nice to expand the "Scientific Metadata" table to use most of the available width in the container.
In the image below, one can see that the table occupy only half of the width of the "Scientific Metadata" Section.
The idea is to minimize the wrapping in the value column and change the ratio to 1:2:1

Change metadata table css in order to show more content

---

src/app/datasets/datasets-filter/datasets-filter.component.ts

Fixes #877
On Chrome (windows and Mac) and Chromium (Linux), `textSearchChanged` in `datasets-filter.component.ts` is expecting a string. On Firefox, this seems to be the case. However, on Chrome, the method is getting many more events, and some come in as Event objects. This turns has the effect updating `input` with the string representation of the event: [object Event].
This fix checks the type of the input and rejects the update if not a string.
The fix seems to work, though I don't fully understand the event model here, so maybe this could have been done more gracefully.

Ignore search events that are not strings

---

src/app/publisheddata/publisheddata-details/publisheddata-details.component.html
src/app/publisheddata/publisheddata.module.ts

Add link from Published Data to the Datasets that are part of it.
As a user, when I'm visiting a published data page, I would like to be able to have a link to the dataset page.
* Add router link from Published Data Details page to Dataset Details page
* Add RouterModule to Published Data Module imports

Add links from published data to datasets

---

src/app/app-routing/app-routing.module.ts
src/app/app-routing/lazy/auth-callback-routing/auth-callback.feature.module.ts
src/app/app-routing/lazy/auth-callback-routing/auth-callback.routing.module.ts
src/app/shared/modules/shared-table/shared-table.module.ts
src/app/users/auth-callback/auth-callback.component.html
src/app/users/auth-callback/auth-callback.component.scss
src/app/users/auth-callback/auth-callback.component.spec.ts
src/app/users/auth-callback/auth-callback.component.ts
src/app/users/login/login.component.html
src/app/users/users.module.ts

This PR aims to add a new component `auth-callback` whose sole purpose is to read query params and update the frontend application state. 
I think it is better to keep it in a different component than the login-component, because of two reasons
- This functionality can be split into another component, which keeps code more readable
- If logic is in the login component then for a split second after redirect you see the input form
SWAP-2835
Added auth-callback component

feat: Adding oauth redirect component

---

src/app/_layout/app-header/app-header.component.html
src/app/app-config.service.spec.ts
src/app/app-config.service.ts
src/app/datasets/dataset-detail/dataset-detail.component.html
src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
src/app/datasets/dataset-file-uploader/dataset-file-uploader.component.ts
src/app/datasets/reduce/reduce.component.ts
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.html
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.spec.ts
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.ts
src/app/shared/sdk/services/custom/Logbook.ts
src/app/shared/services/ownership.service.ts
src/app/state-management/actions/logbooks.actions.ts
src/app/state-management/effects/logbooks.effects.ts
src/app/state-management/reducers/logbooks.reducer.ts
src/assets/config.json

This PR add the following new features:
- show the proposal name even if it is not present. This feature is controlled by option datasetDetailsShowMissingProposalId in config file
- provide logbook access to users that part of dataset access group.
When data is ingest automatically, we do not know if the proposal associated has already been created. The system allows to create a dataset with a proposal id that does not exists in scicat. If that happens we need to be able to display it and follow up with the proper actions.
Logbooks where not accessible to users belonging to access groups. We are going to use the access groups for beam lines scientists and other facility experts and we would like to grant access to every details of the dataset using access groups.

Logbook access and proposal display

---

cypress/integration/datasets-keyword.spec.js
cypress/integration/datasets-metadata.spec.js
src/app/datasets/dataset-detail/dataset-detail.component.html
src/app/datasets/dataset-detail/dataset-detail.component.scss
src/app/datasets/dataset-detail/dataset-detail.component.spec.ts
src/app/datasets/dataset-detail/dataset-detail.component.ts

Users with right access or admins are now allowed to edit the name and description of a given dataset.
There was no way of editing datasets name or description.
* https://jira.esss.lu.se/browse/SWAP-2890
https://user-images.githubusercontent.com/6333063/201943443-f6e54c9d-195d-4467-b548-4668dc9bb136.mp4

feat: Allow for owner groups and admins to edit dataset name and description

---

src/app/app-config.service.spec.ts
src/app/app-config.service.ts
src/app/help/help/help.component.html
src/app/help/help/help.component.spec.ts
src/app/help/help/help.component.ts

It allows to set the some custom messages in the helper
At PSI we need to put a note stating that some links only work internally
* add help message class to config
* retrieve messages from config in help component
* add tests

Allow help messages configuration from config.json

---

src/app/users/login/login.component.html

This PR removes debug message which prints out all oAuth endpoints
There should be no debugged info printed out
Login screen

fix: remove printing oAuth endoints

---

src/app/users/login/login.component.html
src/app/users/login/login.component.spec.ts
src/app/users/login/login.component.ts

When the externalAuth option in the config file is disabled, the hint in the login form defaults to service account
When the externalAuth option in the config file is disabled, the hint in the login form should default to service account
* default hint logic depending on externalAuth in config
* tests

Display "Service" on loginForm if msad enabled

---

src/app/state-management/selectors/datasets.selectors.spec.ts
src/app/state-management/selectors/datasets.selectors.ts

Remove the creationTime from the fullfacet sent fields
As the facet doesn't show the number of items on a particular date, that has been removed from the fields sent to the endpoint
* remove from list

Remove creationTime from fullfacet included params

---

cypress/integration/users-login.spec.js
src/app/_layout/app-header/app-header.component.html
src/app/_layout/app-header/app-header.component.spec.ts
src/app/_layout/app-header/app-header.component.ts
src/app/state-management/actions/user.actions.ts
src/app/state-management/reducers/user.reducer.ts
src/app/users/user-settings/user-settings.component.scss
src/assets/config.json

- fixed logout button not working
- fixed user  token text breakout container issue
- covered e2e test for logout 
and prettier or linter fixed some indentation automatically.
cypress/integration/users-login.spec.js
src/app/_layout/app-header/app-header.component.html
src/app/_layout/app-header/app-header.component.ts
src/app/state-management/actions/user.actions.ts
src/app/users/user-settings/user-settings.component.scss

Fix: user logout button not working

---

src/app/app-config.service.ts
src/app/shared/modules/dialog/dialog.component.html
src/app/shared/modules/dialog/dialog.component.scss
src/app/shared/modules/dialog/dialog.module.ts

Add an optional tooltip to retrieve destinations
The tooltip allows explaining what different retrieve options do
* dialog component displays tooltip with styling

Add optional tooltip to retrieve destinations

---

src/app/app-routing/lazy/instruments-routing/instruments.routing.module.ts
src/app/instruments/instrument-details/instrument-details.component.html
src/app/instruments/instrument-details/instrument-details.component.spec.ts
src/app/instruments/instrument-details/instrument-details.component.ts

Small fix that adds the missing support for tree shaped `customMetadata` of instruments.
In #1022 there is an example of nested metadata for instruments. Without the fix in this merge request, this leads to errors.
Closes #1022 (except that scicatlive will not immediately get the changes, of course) 
* Use `tree-view` to show instrument metadata if `appConfig.metadataStructrue` is `"tree"`
* Use `tree-edit` to edit instrument metadata if `appConfig.metadataStructrue` is `"tree"`
* Implement `OnDestroy` and `EditableComponent` interfaces in `InstrumentDetailsComponent` (necessary for handling the "unsaved changes" warning)
The following changes only apply if `metadataStructure` is set to `"tree"`
Viewing instrument Metadata before:
`ERROR TypeError: cannot use 'in' operator to search for …

Implement tree support for metadata of instruments

---

src/app/state-management/effects/datasets.effects.spec.ts
src/app/state-management/effects/user.effects.spec.ts
src/app/state-management/effects/user.effects.ts
src/app/users/login/login.component.ts
src/app/users/user-settings/user-settings.component.html
src/app/users/user-settings/user-settings.component.ts

1. User identity is fetched after you login with OIDC
2. Copy of user token now excludes Bearer
3. Fixed some other bugs
User identity and settings were not queried after you login with OIDC.
* https://jira.esss.lu.se/browse/SWAP-3085
* https://jira.esss.lu.se/browse/SWAP-3029

remove Bearer from the token in settings and fix oidc login issue with querying userIdentity

---

src/app/datasets/archiving.service.spec.ts
src/app/datasets/archiving.service.ts
src/app/shared/modules/dialog/dialog.component.html

When selecting the retrieve option the first option is preselected
When selecting the retrieve option the first option should be pre-selected and be the value of the first entry. For the same reason, the title is more explicit
* src/app/datasets/archiving.service.ts applies a default

Assign default values on retrieve and change title

---

CI/ESS/e2e/config.e2e.json
cypress/integration/datasets-general.spec.js
cypress/integration/users-login.spec.js
src/app/app-config.service.spec.ts
src/app/app-config.service.ts
src/app/users/login/login.component.html
src/app/users/login/login.component.scss
src/app/users/login/login.component.ts
src/app/users/users.module.ts

Login screen refactored to show external login options first (if any available) with tabular view. Another option for login is local which means login with functional account. Added some e2e tests for it.

refactor: login screen refactored to show external login first

---

src/app/shared/pipes/json-head.pipe.ts

Avoid display  just 'Object' for string metadata in the dataset  table
* use a logic similar the detail page display
- [-] Included for each change/fix?
- [-] Docs updated?
- [-] New packages used/requires npm install? 
- [-] Toggle added for new features?
- [-] Requires update of SciCat backend API?

Fix metadata display in table

---

src/app/datasets/dataset-detail/dataset-detail.component.ts
src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.spec.ts
src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.ts
src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.spec.ts
src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.ts

This PR fixes the bug where string field gets converted to date if you enter numeric value.
If you choose string field type and add a numeric value it gets converted to date type.
* https://jira.esss.lu.se/browse/SWAP-3146

fix: fix metadata wrong type if string has number value

---

src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.html
src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.ts
src/app/proposals/proposal-logbook/proposal-logbook.component.html
src/app/proposals/proposal-logbook/proposal-logbook.component.scss
src/app/proposals/proposal-logbook/proposal-logbook.component.spec.ts
src/app/proposals/proposal-logbook/proposal-logbook.component.ts
src/app/proposals/proposals.module.ts
src/app/proposals/view-proposal-page/view-proposal-page.component.html
src/app/proposals/view-proposal-page/view-proposal-page.component.ts

- feat: created new logbook component for proposal page
- fix: fixed logbook doesn't display issue when proposal have no dataset.
- fix: fixed logbook filter search bar bug  - when search query is empty, it returns event method instead of string value.
New proposal logbook component makes api call based on only proposal id.
Using mixed logic of dataset pid & proposal id based logbook call increases complexity of the component and makes the code hard to maintain.

fix: created proposal-logbook component & fixed few bugs

---

cypress/integration/datasets-attachment.spec.js
src/app/app.module.ts
src/app/shared/interceptors/snackbar.interceptor.ts
src/app/shared/modules/file-uploader/file-uploader.component.html
src/app/shared/modules/file-uploader/file-uploader.component.scss
src/app/shared/modules/file-uploader/file-uploader.component.ts
src/styles.scss

* Add error notification for all errors and success notification on POST, PUT, PATCH or DELETE successful action.
* Improve attachments layout and include download button. (covered this with e2e tests)
There was no feedback if error occurred or something went successfully. Also no way to download attachments.
* https://jira.esss.lu.se/browse/SWAP-3148
* https://jira.esss.lu.se/browse/SWAP-3149
* https://jira.esss.lu.se/browse/SWAP-3150
* https://jira.esss.lu.se/browse/SWAP-3151
* * https://jira.esss.lu.se/browse/SWAP-3152
* changes made

feat: add attachments accepted formats and show success and error notification on each action

---

src/app/datasets/dataset-table/dataset-table.component.html
src/assets/config.json

This PR add the dataset pid as a possible column in the dtaset list
When looking at a list of datasets, at times is useful to be able to visualize the pid of the dataset.
* changed default configuration to include pid
* added element to dataset list element

Added pid to the main dataset table

---

src/app/logbooks/logbooks-detail/logbooks-detail.component.html
src/app/state-management/effects/datasets.effects.spec.ts
src/app/state-management/effects/datasets.effects.ts
src/app/state-management/effects/user.effects.spec.ts
src/app/state-management/effects/user.effects.ts

Update of user settings was done on every visit of the dataset table. We prevent that and fix some unnecessary actions.
Update user settings called unnecessary on every visit of main page
* https://jira.esss.lu.se/browse/SWAP-3174
* changes made

fix: do not make PUT/POST UserSettings request on visiting datasets table

---

CI/ESS/e2e/.env.backend-next
cypress.json
src/app/proposals/view-proposal-page/view-proposal-page.component.ts
src/app/state-management/actions/logbooks.actions.ts
src/app/state-management/effects/logbooks.effects.ts

Switch proposal quickly sometimes causing logbook to not update with changed proposal ID.
https://jira.esss.lu.se/browse/SWAP-3202

fix: proposal logbook sometimes show wrong content

---

src/app/datasets/dataset-detail/dataset-detail.component.html
src/app/datasets/dataset-detail/dataset-detail.component.ts

On the detail page of a dataset is a PID. Normaly the user needs to select manually the PID. This PR adds a input field with simple copy option. 
To deliver more easy a dataset PID add a UX improvement.
* Nothing
* UX improvement
Before:
After:

Change dataset details page PID text to a input field with copy button

---

cypress/integration/users-login.spec.js
src/app/shared/sdk/models/User.ts
src/app/users/user-settings/user-settings.component.html

feat: add auth strategy to the user profile page

---

src/app/datasets/dataset-table/dataset-table.component.ts

on logout only fetch `isPublished:true` datasets' thumbnails
when logout if current page includes not published datasets it throw thumbnail fetch fail errors

fix: thumbnail fetch error on OIDC logout

---

scripts/local.proxy.config.json
src/app/_layout/app-header/app-header.component.ts
src/app/state-management/effects/user.effects.spec.ts
src/app/state-management/effects/user.effects.ts

Use the login route after logout is completed instead of calling it twice.
Login route was called twice instead of making it the right way. This was because the logout endpoint wasn't returning any response. But that is fixed here: https://github.com/SciCatProject/scicat-backend-next/pull/518
* Items added
* changes made

go to /login once logged out directly in the action and not in the component

---

src/app/datasets/archiving.service.ts

CreationDate is always handled by backend now and results in an Error 400 (property creationTime should not exist)
* Don't set creation date on archive/retrieve job creation
- [ - ] Included for each change/fix?
- [ - ] Docs updated?
- [ - ] New packages used/requires npm install? 
- [ - ] Toggle added for new features?
- [ - ] Requires update of SciCat backend API?

Fix archive/retrieve for new BE

---

CI/ESS/e2e/docker-compose.e2e.yaml

This PR aims to fix the startup of backend container after build config is changed.
It depends on this ticket: https://github.com/SciCatProject/scicat-backend-next/pull/823

fix: change backend start command after build config change

---

src/app/datasets/datasets-filter/datasets-filter.component.html
src/app/datasets/datasets-filter/datasets-filter.component.scss

#1297
Fixed condition filter box breaks out when text is too long
**Before**
**After**

fix: condition box breaks out issue

---

.github/workflows/test.yml
CI/ESS/e2e/docker-compose.e2e.yaml

fix: e2e fail

---

.github/dependabot.yml

Dependabot couldn't parse the config file at .github/dependabot.yml. The error raised was:
`(<unknown>): did not find expected key while parsing a block mapping at line 40 column 9`

fix: depandabot yaml wrong format

---

src/app/datasets/related-datasets/related-datasets.component.html
src/app/datasets/related-datasets/related-datasets.component.ts
src/app/shared/sdk/models/BaseModels.ts
src/app/state-management/effects/datasets.effects.spec.ts
src/app/state-management/effects/datasets.effects.ts
src/app/state-management/selectors/datasets.selectors.spec.ts
src/app/state-management/selectors/datasets.selectors.ts

This change addresses issues with the loading and pagination of Related Datasets.
The original code used the wrong interface for data retrieval, resulting in incorrect limit parameters and fetching all available data. Additionally, pagination was incorrect due to the use of wrong parameters.
https://jira.esss.lu.se/browse/SWAP-3633

fix: Related Datasets Loading and Pagination Issues

---

src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.html
src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.scss
src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.ts
src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.html
src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.scss
src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.ts
src/app/shared/modules/scientific-metadata/scientific-metadata.module.ts

Allow users to save units that can not be recognized by the math-js library.
Added a warning message for invalid unit, so that the user aware that the current unit will not be converted.
Some units are missing in the math-js library and thus cannot be converted. We want to allow users to save those unrecognized units as well. 
* changes made

Save metadata with a warning for possible invalid units

---

src/app/datasets/dataset-detail/dataset-detail.component.html

When a dataset doesn't have input datasets, the API returns an empty array. The dataset details would show the label 'Input datasets' without any items/link.
This patch hides the label if the array is empty.

Hide empty 'Input Datasets' on details page

---

src/app/state-management/effects/user.effects.spec.ts
src/app/state-management/effects/user.effects.ts
src/app/users/auth-callback/auth-callback.component.ts

When a user logs in, the loopbackAuth mechanism stores the authentication token in the browser's cookies. However, it fails to automatically remove this token once it has expired. Consequently, when the FetchCurrentUser action attempts to retrieve the user's profile from the backend using this expired JWT token, it results in a 401 Unauthorized error due to the token's invalidity.
* Items added
* changes made

fix: fetchCurrentUser does not validate token expiration time

---

src/app/users/login/login.component.ts

OIDC login fails in the frontend when using version > v4.2.1 and backend v3.x
Make OIDC login available with both backends in `scicatlive`
If possible, can you tag a new version with this fix so we can use it asap in `scicatlive`
#1467

Fix OIDC login with backend v3.x

---

src/app/users/user-settings/user-settings.component.scss

`width: fit-content` attribute causing stretched profile image on safari(17.2.1) and firefox(115.8.0esr)
Removed `width: fit-content` from .profile-image CSS class
src/app/users/user-settings/user-settings.component.scss

fix: fit-content causing strecthed out profile image

---

src/app/users/user-settings/_user-settings-theme.scss
src/app/users/user-settings/user-settings.component.html
src/app/users/user-settings/user-settings.component.scss

Show token partially for security reason.

fix: truncate observable token size

---

package.json
src/app/users/user-settings/user-settings.component.html
src/app/users/user-settings/user-settings.component.spec.ts
src/app/users/user-settings/user-settings.component.ts
tsconfig.json

Updated the application version and improved user settings display.
Enhance user experience by displaying the current app version and facility site information in the user settings.
- Updated app version to 4.4.0. in package.json
- Displayed appVersion and facility in user settings.
- Enabled JSON module resolution in TypeScript configuration.

feat: show release version and site on user settings page

---

src/app/datasets/dashboard/full-text-search/full-text-search-bar.component.html
src/app/datasets/dashboard/full-text-search/full-text-search-bar.component.scss
src/app/datasets/dashboard/full-text-search/full-text-search-bar.component.ts
src/app/datasets/datasets-filter/datasets-filter.component.html
src/app/datasets/datasets-filter/datasets-filter.component.scss
src/app/datasets/datasets-filter/datasets-filter.component.spec.ts

Applied consistent style to search buttons in datasets list. Updated buttons text
This PR applies consistent style and wording to the multiple form buttons present in the datasets list page.
The datasets list page (which is the main page where users spend most of their time) has inconsistent style and text on the multiple buttons present in the text search and filters form.
Please provide a list of the fixes/changes implemented in this PR
* /datasets/dashboard/full-text-search-bar.component: changed html and scss code of the search and clear button
* /datasets/datasets-filter: changed html and scss code of the search and clear button
- which version of the backend is …

Fix: consistent style an dtext on datasets list page

---

src/app/datasets/dashboard/dashboard.component.ts
src/app/state-management/reducers/datasets.reducer.spec.ts
src/app/state-management/reducers/datasets.reducer.ts
src/app/state-management/selectors/datasets.selectors.spec.ts
src/app/state-management/selectors/datasets.selectors.ts
src/app/state-management/state/datasets.store.ts

Attempt to fix pagination

---

src/app/datasets/datafiles-actions/datafiles-action.component.spec.ts
src/app/datasets/datafiles-actions/datafiles-action.component.ts
src/app/datasets/datafiles-actions/datafiles-action.interfaces.ts
src/app/datasets/datafiles-actions/datafiles-actions.component.ts
src/assets/config.json

this PR solves the datafiles actions bug highlighted in #1550. The only method supported is by form and it is submitted. I also changed the code to expand in the future to other actions type like using fetch api.
When we added datafiles actions we did not attached the form to the body therefore was not submitted. 
- datafiles-action files
- [] Does it require a specific version of the backend

fix: solved form submission in datafiles actions

---

src/app/datasets/admin-tab/admin-tab.component.ts
src/app/datasets/archiving.service.spec.ts
src/app/datasets/archiving.service.ts
src/app/datasets/datafiles-actions/datafiles-action.component.spec.ts
src/app/datasets/datafiles/datafiles.component.ts
src/app/jobs/jobs-dashboard-new/jobs-dashboard-new.component.ts
src/app/jobs/jobs-dashboard/jobs-dashboard.component.spec.ts
src/app/jobs/jobs-dashboard/jobs-dashboard.component.ts
src/app/jobs/jobs-detail/jobs-detail.component.html
src/app/jobs/jobs-detail/jobs-detail.component.scss
src/app/shared/modules/shared-table/_shared-table-theme.scss
src/app/shared/sdk/models/Job.ts
src/app/state-management/effects/jobs.effects.spec.ts
src/app/state-management/reducers/jobs.reducer.spec.ts
src/app/state-management/selectors/jobs.selectors.spec.ts

Make a first try to see whether the MVP `release-jobs` backend is compatible with the frontend.
To make the frontend compatible with the new Jobs schema from the `release-jobs` backend, we have to update the job list page, the job detail page, the schema in the frontend and all its references to it, as well as the `.spec` test files.
- https://github.com/SciCatProject/frontend/issues/1138
- https://github.com/SciCatProject/frontend/issues/1139
- https://github.com/SciCatProject/frontend/issues/1140
- Provide new job schema in `src/app/shared/sdk/models/Job.ts` by updating the definition of `Job` class 
- Update the relevant fields whenever an instance of the `Job` class is created:
- provide `datasetIds` inside `jobParams`
- rename `emailJobInitiator` to `createdBy` and its value should …

Update frontend to match with release-jobs backend

---

src/app/app-config.service.ts
src/app/app.component.ts
src/app/datasets/admin-tab/admin-tab.component.spec.ts
src/app/datasets/dashboard/dashboard.component.ts
src/app/datasets/datasets-filter/datasets-filter.component.html
src/app/datasets/datasets-filter/datasets-filter.component.ts
src/app/datasets/datasets-filter/settings/datasets-filter-settings.component.html
src/app/datasets/datasets-filter/settings/datasets-filter-settings.component.scss
src/app/datasets/datasets-filter/settings/datasets-filter-settings.component.ts
src/app/shared/modules/filters/date-range-filter.component.ts
src/app/shared/modules/filters/filters.module.ts
src/app/shared/modules/filters/group-filter.component.ts
src/app/shared/modules/filters/interface/filter-component.interface.ts
src/app/shared/modules/filters/keyword-filter.component.ts
src/app/shared/modules/filters/location-filter.component.ts
src/app/shared/modules/filters/pid-filter-contains.component.ts
src/app/shared/modules/filters/pid-filter-startsWith.component.ts
src/app/shared/modules/filters/pid-filter.component.spec.ts
src/app/shared/modules/filters/pid-filter.component.ts
src/app/shared/modules/filters/text-filter.component.ts
src/app/shared/modules/filters/type-filter.component.ts
src/app/shared/modules/filters/utils.ts
src/app/shared/sdk/services/custom/User.ts
src/app/state-management/effects/user.effects.ts
src/app/state-management/models/index.ts
src/app/state-management/reducers/user.reducer.ts
src/app/state-management/state/user.store.ts
src/assets/config.json

This PR aims to separate frontend configuration from the backend, making the frontend more autonomous and reducing backend dependencies.
NOTE: Once its merged, tests need to be modified.
To improve flexibility and maintainability while reducing unnecessary backend dependencies.
- Replaced references to localColumns with defaultDatasetsListSettings.columns with backward compatibility .
- Added defaultDatasetsListSettings to AppConfig for default filters, columns, and conditions in the dataset list.
- Introduced labelMaps to store filter labels in AppConfig. If not provided, fallback to `component.instance.label`.
- Removed get default settings endpoint.
- which version of …

refactor: decouple default search UI interface logic from backend

---

.github/workflows/test.yml
package-lock.json
package.json
src/app/shared/sdk/models/FireLoopRef.ts
src/app/shared/sdk/sockets/socket.connections.ts
src/app/state-management/effects/user.effects.spec.ts

Please provide a list of the fixes implemented in this PR
* Items added
Please provide a list of the changes implemented by this PR
* changes made

build: update "RxJS" and "jasmine-marbles" version
