src/app/app.component.html, src/app/app.component.scss, src/app/datasets/datablocks-table/datablocks-table.component.spec.ts, src/app/datasets/datafiles/datafiles.component.html, src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/datasets/dataset-detail/dataset-detail.component.scss, src/app/datasets/dataset-table/dataset-table.component.scss, src/app/users/login/login.component.css, src/app/users/login/login.component.html, src/app/users/login/login.component.spec.ts, src/app/users/login/login.component.ts, src/app/users/users.module.ts
Improves the layout.
Currently, the layout uses Material cards in a nested way, which quite defeats their purpose and reduces the "3d feel" of the layout.
* Whole page isn't any longer wrapped in a big <mat-card>
* Login page uses material checkbox
=> WIP: Feature/update layout

src/app/app.component.html, src/app/app.component.ts, src/app/state-management/reducers/user.reducer.ts, src/app/state-management/state/user.store.ts
partial work towards Unify authentication methods #23
TOTAL: 143 SUCCESS
16 08 2018 16:29:40.109:DEBUG [karma]: Run complete, exiting.
16 08 2018 16:29:40.110:DEBUG [launcher]: Disconnecting all browsers
16 08 2018 16:29:40.164:DEBUG [launcher]: Process Chrome exited with code 0
16 08 2018 16:29:40.164:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-93588499
16 08 2018 16:29:40.170:DEBUG [launcher]: Finished all browsers
=> Issue #23 fixes to username resolving

src/app/datasets/dataset-detail/dataset-detail.component.ts
=> Issue #39 remove call to pipe

src/app/shared/sdk/index.ts, src/app/shared/sdk/models/Policy.ts, src/app/shared/sdk/models/PublishedData.ts, src/app/shared/sdk/models/index.ts, src/app/shared/sdk/services/custom/PublishedData.ts, src/app/shared/sdk/services/custom/SDKModels.ts, src/app/shared/sdk/services/custom/index.ts
updating SDK to include published data, see Issue #55
add latest catamel SDK to catanie
* added publisheddata model to catanie SDK
* changes made
[X] Passing? (Merge will not be approved unless this is checked) 
=> updating SDK, see Issue #55

src/app/state-management/reducers/datasets.reducer.ts
very small change to dataset reducers. Relevant action not referenced by reducer.
=> Issue #68 fixed datablocks state management bug

src/app/jobs/jobs-detail/jobs-detail.component.ts
Background on use case, chnages needed
* Items added
* changes made
=> fix typo in observable

src/app/state-management/effects/user.effects.ts, src/app/state-management/reducers/user.reducer.spec.ts, src/app/state-management/reducers/user.reducer.ts
Removes commented out code. No functional changes
=> Removed commented out code and imports

package-lock.json, src/app/datasets/datablocks-table/datablocks-table.component.spec.ts, src/app/datasets/datafiles/datafiles.component.spec.ts, src/app/datasets/dataset-detail/dataset-detail.component.spec.ts, src/app/datasets/dataset-form/dataset-form.component.spec.ts, src/app/datasets/dataset-form/dataset-form.component.ts, src/app/datasets/dataset-table/dataset-table.component.spec.ts, src/app/datasets/datasets-filter/datasets-filter.component.spec.ts, src/app/datasets/file-dropzone/file-dropzone.component.spec.ts, src/app/datasets/file-picker/file-picker.component.spec.ts, src/app/jobs/jobs-table/jobs-table.component.spec.ts, src/app/proposals/components/proposals-list/proposals-list.component.spec.ts, src/app/sample-data-form/sample-data-form.component.spec.ts, src/app/shared/MockStubs.ts, src/app/shared/modules/breadcrumb/breadcrumb.component.spec.ts, src/app/shared/modules/config-form/config-form.component.spec.ts, src/app/shared/modules/error-page/error-page.component.spec.ts, src/app/state-management/actions/datasets.actions.spec.ts, src/app/state-management/actions/proposals.actions.spec.ts, src/app/state-management/state/policies.store.ts, src/app/users/user-details/user-details.component.spec.ts, src/app/users/user-settings/user-settings.component.spec.ts
Random unit test failures
See issue #106 
* fixes issue #106 
*  add fixtures.destroy() to problematic unit tests
=> Random unit test failures

src/app/datasets/dataset-table/dataset-table.component.ts
=> removed path from dlg

package-lock.json, src/app/app.component.scss, src/app/datasets/datasets-filter/datasets-filter.component.css, src/app/datasets/datasets-filter/datasets-filter.component.html, src/app/datasets/datasets-filter/datasets-filter.component.spec.ts, src/app/datasets/datasets-filter/datasets-filter.component.ts, src/app/datasets/datasets.module.ts, src/app/datasets/scientific-condition-dialog/scientific-condition-dialog.component.html, src/app/datasets/scientific-condition-dialog/scientific-condition-dialog.component.ts, src/app/state-management/actions/datasets.actions.ts, src/app/state-management/models/index.ts, src/app/state-management/reducers/datasets.reducer.spec.ts, src/app/state-management/reducers/datasets.reducer.ts, src/app/state-management/selectors/datasets.selectors.ts, src/app/state-management/state/datasets.store.ts
Introduces scientific metadata conditions, added using a dialog through the filter box next to the dataset table. It is not connected with the backend yet (work needed).
=> WIP: Feature/scientific query

src/app/datasets/batch-view/batch-view.component.ts, src/app/datasets/dataset-table/dataset-table.component.ts, src/app/state-management/effects/jobs.effects.ts, src/app/state-management/effects/user.effects.ts, src/app/state-management/models/index.ts, src/app/state-management/reducers/user.reducer.spec.ts, src/app/state-management/state/user.store.ts
force definition of duration param
=> Issue #77 force definition of duration param

package-lock.json, package.json
remove compodoc and get rid of event-stream
remove compodoc and get rid of event-stream as it contains a vulnerability
* Items added
* changes made
[x] New packages used/requires npm install?
=> remove compodoc and get rid of event-stream

src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/datasets/dataset-detail/dataset-detail.component.spec.ts, src/app/datasets/dataset-detail/dataset-detail.component.ts, src/app/proposals/components/proposal-detail/proposal-detail.component.html, src/app/proposals/components/proposal-detail/proposal-detail.component.spec.ts, src/app/proposals/components/proposal-detail/proposal-detail.component.ts
Add link from dataset to proposal
Summary
We need to link from proposal table to relevant dataset
and from dataset detail page to relevant proposal
=> Add link from dataset to proposal

src/app/users/login/login.component.ts
navigatebyURL to previous url after logging in
See Issue #147 
* fixes #147 
* added url redirection to specific dataset
=> navigatebyURL to previous url after logging in

src/app/jobs/jobs-table/jobs-table.component.ts, src/app/state-management/actions/jobs.actions.spec.ts, src/app/state-management/actions/jobs.actions.ts, src/app/state-management/effects/jobs.effects.ts, src/app/state-management/reducers/jobs.reducer.ts, src/app/state-management/selectors/jobs.selectors.ts, src/app/state-management/state/jobs.store.ts
Issue #191 fixed paging in jobs table
=> Issue #191 fixed paging in jobs table

src/app/datasets/dataset-detail/dataset-detail.component.ts, src/app/datasets/dataset-table/dataset-table.component.html
As for Issue #194 
* Items added
* changes made
=> Issue #194 minor gui changes

src/app/datasets/datafiles/datafiles.component.ts
As per Issue #182 fixed dataFiles table slow down
=> Issue #182 fixed dataFiles table slow down

src/app/jobs/jobs-table/jobs-table.component.ts, src/app/state-management/actions/jobs.actions.spec.ts, src/app/state-management/actions/jobs.actions.ts, src/app/state-management/effects/jobs.effects.ts, src/app/state-management/reducers/jobs.reducer.spec.ts, src/app/state-management/reducers/jobs.reducer.ts
Remove unreferenced code from jobs causing error in CI
=> Remove unreferenced code from jobs causing error in CI

src/app/datasets/datafiles/datafiles.component.html, src/app/datasets/datafiles/datafiles.component.ts
Issue #208 
also fixed console error relating to jwt.
=> fixed console error about expression chaning after being checked

src/app/jobs/jobs-detail/jobs-detail.component.html, src/app/jobs/jobs-table/jobs-table.component.html, src/app/jobs/jobs-table/jobs-table.component.ts
remove dataset column from jobs table
performance problems on production. Not repeatable on QA or develop
=> remove dataset column from jobs table

src/app/jobs/jobs-detail/jobs-detail.component.html, src/app/jobs/jobs-table/jobs-table.component.html
add time to created at column jobs table
=> add time to created at column

src/app/datasets/dataset-table/dataset-table.component.html, src/app/datasets/dataset-table/dataset-table.component.spec.ts, src/app/shared/pipes/numeric.pipe.spec.ts, src/app/shared/pipes/numeric.pipe.ts, src/app/shared/shared.module.ts
So I solved it with a new pipe, that strips non-numeric characters from a string. I'm not sure if that's an overkill for such a simple task, but I trying to follow the general conventions, which appears to be using pipes for these types of transformations.
The name of the pipe might be a bit misleading as well; I was trying to with something short.
=> new pipe for stripping non-numeric characters from a string

src/app/state-management/actions/user.actions.ts, src/app/state-management/effects/user.effects.ts, src/app/state-management/reducers/user.reducer.ts, src/app/state-management/selectors/users.selectors.ts, src/app/users/login.service.ts
=> user profile in store

src/app/state-management/actions/datasets.actions.ts, src/app/state-management/effects/datasets.effects.ts
Adding actions to dataset effects output
Issue #244 
* fixes #244 
* changes made
=> add action to dataset effect

src/app/proposals/components/proposal-detail/proposal-detail.component.html, src/app/proposals/components/proposal-detail/proposal-detail.component.spec.ts, src/app/proposals/components/proposal-detail/proposal-detail.component.ts, src/app/proposals/proposals.module.ts, src/app/state-management/actions/proposals.actions.ts, src/app/state-management/reducers/proposals.reducer.ts, src/app/state-management/selectors/proposals.selectors.ts, src/app/state-management/state/proposals.store.ts
add paging to proposal dataset table
Issue #221
=> Add paging to proposals Issue #221

src/app/proposals/components/proposal-detail/proposal-detail.component.spec.ts
it seems merge request #249 broke the unit tests.
the call to StoreModule.forRoot() was too broad.
reduce the range of state brought into the proposal detail unit test
=> fix unit tests

package-lock.json, package.json, src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/datasets/datasets.module.ts
Issue #284 
Use ngx-json-viewer for metadata display on dataset details
[x Passing? (Merge will not be approved unless this is checked) 
[x] New packages used/requires npm install? 
[no] Toggle added for new features?
=>  Use ngx-json-viewer

src/app/state-management/effects/user.effects.ts
trigger get profile action on login to populate the profile state
Utilise/ use the user profile state that has already been implemented.
=> trigger get profile action on login to populate the profile state

src/app/state-management/effects/user.effects.ts, src/app/state-management/selectors/users.selectors.ts, src/app/users/user-settings/user-settings.component.ts
dont fetch profile for functional users
=> dont fetch profile for functional users

src/app/state-management/effects/jobs.effects.ts
Issue #220
after a job action failed, no new actions were observed.
This is a classic misuse of catchError.
https://medium.com/city-pantry/handling-errors-in-ngrx-effects-a95d918490d9
=> Issue #220 fixed catchError missue

src/app/state-management/effects/datasets.effects.ts, src/app/state-management/effects/jobs.effects.ts, src/app/state-management/effects/policies.effects.ts, src/app/state-management/effects/proposals.effects.ts, src/app/state-management/effects/user.effects.ts
Ensure catchError does not terminate the observable, but switches back to success state when appropriate
Issue #220
=> ensure catchError is being used correctly.

src/app/datasets/column-selector/column-selector.component.ts, src/app/datasets/dataset-table/dataset-table.component.html, src/app/datasets/dataset-table/dataset-table.component.scss, src/app/state-management/actions/datasets.actions.ts, src/app/state-management/effects/policies.effects.ts, src/app/state-management/models/index.ts, src/app/state-management/reducers/datasets.reducer.spec.ts, src/app/state-management/reducers/datasets.reducer.ts, src/app/state-management/selectors/datasets.selectors.spec.ts, src/app/state-management/selectors/datasets.selectors.ts, src/app/state-management/state/datasets.store.ts, src/app/state-management/state/user.store.ts
issue #290 
add archive/ retrieve status icon column
fix view mode toggle router persistence issue on refresh (prefill filters)
UX workshop
[x] Toggle added for new features?
=> Feature/row icons issue #290 

src/app/datasets/dataset-table/dataset-table.component.html, src/app/datasets/dataset-table/dataset-table.component.ts, src/app/state-management/models/index.ts, src/app/state-management/reducers/datasets.reducer.ts
Issue #317 Enhance dataset status toggle filters.
added two new toggle buttons within the archive workflow functionality
=> enhance data status filter toggles to include error info

src/app/state-management/reducers/datasets.reducer.ts
Issue #320 reset page on filter mode selection
=> reset table page when changing mode toggle

src/app/datasets/dataset-detail/dataset-detail.component.html
add link to orcid to dataset
* fixes #323 
* changes made
=> add link to orcid

src/environments/environment.dev.ts
not sure if it is relevant for anyone
=> environment.dev: minor typo in IP address

src/app/logbooks/logbook.service.ts
Implemented rison to avoid parsing errors in requests
* Items added
* changes made
[X] Included for each change/fix?
[X] Passing? (Merge will not be approved unless this is checked) 
=> Added rison encoder to Logbook service

package-lock.json, package.json, src/app/datasets/publish/publish.component.ts
use publish form prefill endpoint
=> use prefill endpoint

src/app/about/about/about.component.ts, src/app/app.component.html, src/app/app.component.scss, src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/datasets/dataset-detail/dataset-detail.component.spec.ts, src/app/help/help/help.component.html, src/app/shared/pipes/index.ts, src/app/shared/pipes/replace-underscore.pipe.spec.ts, src/app/shared/pipes/replace-underscore.pipe.ts, src/app/shared/shared.module.ts
move menu items to right side 
add icons and make clearly options
* fixes #334 
* changes made
=> make menu items clearly distinguishable

src/app/about/about.module.ts, src/app/about/about/about.component.html, src/app/about/about/about.component.spec.ts, src/app/about/about/about.component.ts
Adding link for re3data people
requirements to register as data repostitory
* Items added
* changes made
=> add updated link to ess

src/app/logbooks/logbooks-detail/logbooks-detail.component.html
Logbook detail view now supports showing entries written in markdown
The feature was requested at the demo of the logbook
Added some conditionals to the logbooks-detail.component.html
[*] Passing? (Merge will not be approved unless this is checked) 
=> Added markdown support for the logbook detail view

src/app/publisheddata/publisheddata-details/publisheddata-details.component.html, src/app/publisheddata/publisheddata-details/publisheddata-details.component.ts, src/app/publisheddata/publisheddata-table/publisheddata-table.component.html, src/app/publisheddata/publisheddata-table/publisheddata-table.component.ts, src/app/state-management/actions/published-data.actions.ts, src/app/state-management/effects/published-data.effects.ts, src/app/state-management/reducers/logbooks.reducer.ts, src/app/state-management/reducers/published-data.reducer.ts, src/app/state-management/reducers/root.reducer.ts, src/app/state-management/selectors/published-data.selectors.ts, src/app/state-management/state/publishedData.store.ts
change actions that operate on the store to trigger api call
=> abandon entity style actions

src/app/publisheddata/publisheddata-details/publisheddata-details.component.ts, src/app/publisheddata/publisheddata-table/publisheddata-table.component.html, src/app/publisheddata/publisheddata-table/publisheddata-table.component.spec.ts, src/app/publisheddata/publisheddata-table/publisheddata-table.component.ts, src/app/state-management/actions/published-data.actions.ts, src/app/state-management/effects/published-data.effects.ts, src/app/state-management/reducers/published-data.reducer.ts, src/app/state-management/selectors/published-data.selectors.ts
as it says on the tin. Routing for published data
=> browser routing for pub

src/app/datasets/publish/publish.component.ts, src/app/state-management/effects/published-data.effects.ts, src/environments/environment.v20.ts
chain create published data with a call to register
=> chain create published data with a call to register

src/app/app-config.module.ts, src/app/datasets/dataset-table/dataset-table.component.html, src/environments/environment.dmscprod.ts, src/environments/environment.ts
remove color bar for psi
see issue #264 
* fixes #264
* changes made
=> remove colorbar option

src/app/app-routing/app-routing.module.ts, src/app/policies/policies.module.ts, src/app/policies/policies/policies.component.ts
=> private member to public for travis build

src/app/datasets/dataset-form/dataset-form.component.ts, src/app/proposals/components/proposal-detail/proposal-detail.component.html, src/app/proposals/components/proposal-detail/proposal-detail.component.ts, src/app/proposals/components/proposals-list/proposals-list.component.html, src/app/proposals/proposals.module.ts, src/app/state-management/reducers/proposals.reducer.ts
add measurement list  to proposal view
and also seed proposal id and authors in proposal list
* fixes #376 
* changes made
=> add measurement list  to proposal view

src/app/logbooks/logbooks-detail/logbooks-detail.component.html, src/app/state-management/reducers/logbooks.reducer.ts
properly check for null objects
quite a few places where object.prop.length === ... is used where !object.prop should be used.
Fixed this to some extent. needs full review
=> properly check for null objects

src/app/proposals/components/proposal-detail/proposal-detail.component.spec.ts, src/app/proposals/components/proposals-list/proposals-list.component.html, src/app/proposals/components/proposals-list/proposals-list.component.spec.ts, src/app/proposals/components/proposals-list/proposals-list.component.ts, src/app/proposals/containers/list-proposals-page/list-proposals-page.component.ts, src/app/proposals/proposals.service.ts, src/app/publisheddata/publisheddata.service.ts, src/app/state-management/actions/datasets.actions.ts, src/app/state-management/actions/proposals.actions.ts, src/app/state-management/effects/policies.effects.ts, src/app/state-management/effects/proposals.effects.ts, src/app/state-management/reducers/proposals.reducer.ts, src/app/state-management/selectors/proposals.selectors.ts, src/app/state-management/state/datasets.store.ts, src/app/state-management/state/proposals.store.ts
Add table to proposals
See #380 
* Items added
* changes made
=> WIP Feature/table proposal

src/app/policies/policies.service.ts, src/app/shared/sdk/services/custom/Policy.ts
inline with updateWhere endpoint changes
=> update policy SDK

src/app/help/help/help.component.html
Add more help to scicat, linking to proposals and samples
* Items added
* changes made
=> add proposal help

src/app/proposals/components/proposals-list/proposals-list.component.html, src/app/proposals/components/proposals-list/proposals-list.component.ts, src/app/proposals/containers/list-proposals-page/list-proposals-page.component.ts, src/app/state-management/actions/proposals.actions.ts, src/app/state-management/effects/proposals.effects.ts, src/app/state-management/reducers/proposals.reducer.ts, src/app/state-management/selectors/proposals.selectors.ts
Implement proposals table standard functionality
* changes made
=> Implement proposals table standard functionality

src/app/datasets/dataset-detail/dataset-detail.component.html
Adds links to input datasets in the dataset detail view
Requested in issue #280 
* Added loop over input datasets array containing routerLink to dataset
=> Added links to input datasets in detail view

src/app/datasets/datafiles/datafiles.component.html, src/app/datasets/dataset-table/dataset-table.component.html, src/app/jobs/jobs-table/jobs-table.component.html, src/app/policies/policies/policies.component.html, src/app/proposals/components/proposal-detail/proposal-detail.component.html, src/app/proposals/components/proposals-list/proposals-list.component.html, src/app/publisheddata/publisheddata-table/publisheddata-table.component.html, src/app/samples/sample-table/sample-table.component.html
Added beginning and end buttons to material-paginate
Requested in issue #359 
* Added property 'showFirstLastButtons' to all mat-paginator tags
=> Added property `showFirstLastButtons` to all material paginators

src/app/policies/policies/policies.component.ts
=> determine application of policy settings

src/app/datasets/publish/publish.component.ts, src/app/datasets/reduce/reduce.component.html, src/app/state-management/actions/published-data.actions.ts, src/app/state-management/effects/published-data.effects.ts, src/app/state-management/reducers/published-data.reducer.ts, src/app/state-management/state/publishedData.store.ts
use state management for publication, display message to user, redirect to published data details upon success
=> pub redirect etc

src/app/state-management/effects/published-data.effects.ts
encode doi before registering
* Items added
* changes made
=> encode doi to post

src/app/_layout/login-header/login-header.component.html, src/app/app-routing/app-routing.module.ts
Fixes the issue of the dissapearing user menu when clicking on help or about link
See issue #446 
* Fixes #446 
* Changed LoginLayout routing for help and about pages
* Updated links in LoginHeaderComponent to accomodate routing change
=> Changed routing for help and about in LoginLayout

src/app/datasets/dataset-detail/dataset-detail.component.ts, src/app/state-management/effects/datasets.effects.ts, src/app/state-management/effects/proposals.effects.ts, src/app/state-management/effects/samples.effects.ts
Removed obosolete attachment related console printouts 
Obsolete
* Removed attachment related console printouts from effects and dataset details component
=> Removed obsolete console printouts related to attachments

.travis.yml, package-lock.json, package.json
Added coveralls to devDependencies
Increase code coverage
* Added coveralls to devDependencies
=> Added coveralls to devDependencies

src/app/datasets/dataset-table/dataset-table.component.html
add .value to runnumber 
in line with other scientificMetadata
* Items added
* changes made
=> add value to runnumber

src/app/datasets/datablocks-table/datablocks-table.component.ts, src/app/datasets/datafiles/datafiles.component.html, src/app/datasets/datafiles/datafiles.component.scss, src/app/datasets/datafiles/datafiles.component.ts
checkbox on dataset files changes from grey to  white 
#506 
* fixes #506 
* changes made
=> change dataset files table header to white on blue background

src/app/datasets/datafiles/datafiles.component.html, src/app/datasets/datafiles/datafiles.component.scss, src/app/datasets/datafiles/datafiles.component.ts, src/styles.css
Makes it possible to download a single file by clicking on the file name
Was broken due to the implementation of zip service
* Added the zip service form to the path column in the table
=> Added zip service form to table path column

src/app/app-config.module.ts, src/app/users/login/login.component.html, src/environments/environment.dmscdev.ts, src/environments/environment.ts
add username prompt on login 
see #539 
* fixes #539
* changes made
=> add username prompt

src/app/app-config.module.ts, src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.html, src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.scss, src/environments/environment.dmscdev.ts, src/environments/environment.dmscprod.ts, src/environments/environment.ts
Added button that links dataset to jupyter hub
Requested
* Added button with link to jupyter hub in dataset details dashbaord
* Added jupyterHubUrl variable to environment
=> Added jupyter hub button to dataset details dashboard

src/app/publisheddata/publisheddata-details/publisheddata-details.component.html, src/app/publisheddata/publisheddata-details/publisheddata-details.component.ts, src/app/shared/sdk/models/PublishedData.ts
=> update sdk and minor change

src/app/datasets/dataset-detail/dataset-detail.component.html
Added access groups to dataset details
Requested
* Added access groups property to dataset details
* Made principal investigator email into a link
=> Added access groups to dataset details + made pi email link

src/app/datasets/batch-view/batch-view.component.html, src/app/datasets/batch-view/batch-view.component.scss, src/app/datasets/batch-view/batch-view.component.ts
Added theme colors to batch view table
Consistency
* Added theme colors to batch view table
* Cleaned up css
=> Added theme colors to batch table

src/app/datasets/dataset-table/dataset-table.component.ts
re add code removed by mistake
- [x ] Passing? (Merge will not be approved unless this is checked)
=> re add code removed by mistake

src/app/datasets/publish/publish.component.ts, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts, src/app/publisheddata/publisheddata-details/publisheddata-details.component.html, src/app/shared/sdk/models/PublishedData.ts
add scicat user to published data table and detail
- [ x] Passing? (Merge will not be approved unless this is checked)
=> add scicat user to published data table and detail

src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.spec.ts, src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.ts
Fixed bug where sample characteristics edit would retain state from previous sample
Bug fix
* Added OnChanges to metadata edit component
=> Added onChanges to metadata edit component

src/app/jobs/jobs-dashboard/jobs-dashboard.component.html, src/app/jobs/jobs-dashboard/jobs-dashboard.component.ts, src/app/state-management/effects/jobs.effects.spec.ts, src/app/state-management/effects/jobs.effects.ts, src/app/state-management/effects/policies.effects.spec.ts, src/app/state-management/effects/policies.effects.ts, src/app/state-management/reducers/jobs.reducer.spec.ts, src/app/state-management/reducers/jobs.reducer.ts, src/app/state-management/reducers/policies.reducer.spec.ts, src/app/state-management/reducers/policies.reducer.ts
add sorting to jobs, fix sorting direction (should be space separated)
issue #590 
- [ x] Passing? (Merge will not be approved unless this is checked)
=> add sorting to jobs, fix sorting direction (should be space separated)

src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.html, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts, src/app/state-management/actions/published-data.actions.ts, src/app/state-management/effects/published-data.effects.ts, src/app/state-management/reducers/published-data.reducer.ts, src/environments/environment.ts
enable sorting in published data table
remove obsolete environment config item
=> allow sorting published data, remove obsolete env item

src/app/state-management/effects/proposals.effects.ts
as the proposal contains "/" it needs to be encoded to %2F in api calls.
=> proposal id needs encoding for find

src/app/datasets/dataset-table/dataset-table.component.scss
Updated dataset table column width styling.
Requested
* Brought flex back in column styling to shrink short string columns
=> Updated column width styling

src/app/state-management/effects/logbooks.effects.ts
Wrapped proposalId in encodeURIComponent for logbook fetches.
See issue #599 
* Fixes #599 
* Wrapped proposalId in encodeURIComponent for logbook fetches.
=> Added encodeURIComponent to logbook effects

src/tsconfig.json
Add es2017 to tsconfig.json
see issue #615 
* fixes #615
* changes made
=> fix build error in typescript

src/app/datasets/publish/publish.component.ts, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts, src/app/publisheddata/publisheddata-details/publisheddata-details.component.html, src/app/publisheddata/publisheddata-details/publisheddata-details.component.scss, src/app/publisheddata/publisheddata-details/publisheddata-details.component.ts, src/app/state-management/effects/published-data.effects.spec.ts, src/app/state-management/effects/published-data.effects.ts
Seperate the creation of a published data item with the registration of the assoc. DOI
Add status indicator and register button to published data detail
=> Separate the creation of a published data item with the registration of the assoc. DOI

src/app/datasets/anonymous-details-dashboard/anonymous-details-dashboard.component.html, src/app/datasets/anonymous-details-dashboard/anonymous-details-dashboard.component.scss
Add datafiles tab to anonymous dataset details view.
Make it possible for anonymous users to download public data files.
* Add datafiles tab to anonymous dataset details view.
=> Add file view to anonymous dataset details

.github/workflows/gitlab.yml
I added a job trigger for Max IV
Needed to deploy our test site
* Items added
* changes made
=> added job trigger for Max IV

.github/workflows/ci.yml, CI/MAXIV/Dockerfile
=> change ci branch

src/app/shared/modules/scientific-metadata-tree/base-classes/tree-base.ts
I realized that I missed the case when value can be an array in `{unit:"", value:[1,2,3]}`.
=> add support for array

src/app/app-routing/app-routing.module.ts, src/app/proposals/proposal-dashboard-new/proposal-dashboard-new.component.html, src/app/proposals/proposal-dashboard-new/proposal-dashboard-new.component.spec.ts, src/app/proposals/proposal-dashboard-new/proposal-dashboard-new.component.ts, src/app/proposals/proposals.module.ts
This PR solves issue #756 
See issue #756
Fixed the filter issue
- Using ShareTableComponent instead
- Removed "Author" column (Not sure how to get both firstname and lastname to show up in one column. Change in Share table is required to do that).
=> Shared table for proposal dashboard

CI/MAXIV/maxiv-theme.scss
Small changes to the Max IV theme file in CI/MAXIV/ this doesn't affect any other deployment apart of the Max IV one.
SciCat theming was changed recently this is a needed update the theme file for the Max IV facility to show, again, the colors as it's supposed to do.
* Changed the CI/MAXIV/maxiv-theme.scss
=> Copied new style and added the Max IV colors to the theme

package-lock.json, package.json, src/app/datasets/dataset-table/dataset-table.component.html, src/app/datasets/dataset-table/dataset-table.component.ts, src/app/shared/modules/scientific-metadata-tree/base-classes/tree-base.ts, src/app/shared/modules/search-parameters-dialog/search-parameters-dialog.component.html, src/app/shared/modules/search-parameters-dialog/search-parameters-dialog.module.ts, src/app/shared/pipes/stripProposalPrefix.pipe.ts
There are custom columns that show values in requested unit. This works for flat metadata but not nested. This PR adds support for nested metadata.
=> Show values in custom column

CI/MAXIV/Dockerfile, CI/MAXIV/index.html
=> Google fonts

src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/datasets/dataset-detail/dataset-detail.component.ts
=> Properly initialize datasetWithout$ and attachments$

.betterer.results, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.html, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.spec.ts, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts, src/app/state-management/selectors/published-data.selectors.spec.ts, src/app/state-management/selectors/published-data.selectors.ts
View model selector for published data dashboard.
Cleaner code in components.
* Create selectPublishedDataDashboardPageViewModel selector
* Replace individual selectors in published data dashboard with selectPublishedDataDashboardPageViewModel selector
=> Set up published data dashboard page view model selector

src/app/shared/services/scicat-data-service.ts
See #905 
See #905 
- Removed private variable for token in `ScicatDataService`
=> Fix empty proposal table

src/app/shared/services/scicat-data-service.ts
Add Authorization header to `/fullquery` and `/fullfacet` requests in SciCat Data Service.
The new backend implementation will only accept token sent in header. With this change, SciCat Data Service will be compliant with both the current and the next backend implementation.
* Add Authorization header to `/fullquery` and `/fullfacet` requests in SciCat Data Service.
=> Add Authorization header in scicat data service

src/app/datasets/archiving.service.ts, src/app/datasets/dashboard/dashboard.component.ts, src/app/datasets/dataset-detail/dataset-detail.component.ts, src/app/jobs/jobs-detail/jobs-detail.component.ts, src/app/samples/sample-dashboard/sample-dashboard.component.ts, src/app/samples/sample-detail/sample-detail.component.ts, src/app/users/user-settings/user-settings.component.spec.ts
Fix issues pointed out by DeepScan.
Clean up code.
=> Fix deepscan issues

cypress/fixtures/derivedDataset.json, cypress/fixtures/rawDataset.json
This PR aims to fix the e2e tests after some backend changes on the input validation.
=> test: Fix e2e tests by removing some dataset fields that are not needed anymore

src/app/shared/sdk/services/custom/Policy.ts
Fix for the e2e tests that are broken because of the changes here: https://github.com/SciCatProject/scicat-backend-next/pull/196
=> fix e2e tests after backend changes

cypress/integration/policy-delegate.spec.js, cypress/support/commands.js
Fixing and improving policy e2e tests.
e2e tests failing
=> fix e2e tests

cypress/fixtures/proposal.json, cypress/fixtures/rawDataset.json, cypress/integration/datasets-general.spec.js, cypress/support/commands.js, src/app/datasets/dashboard/dashboard.component.spec.ts, src/app/datasets/dashboard/dashboard.component.ts, src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/state-management/effects/datasets.effects.spec.ts, src/app/state-management/effects/datasets.effects.ts
=> fix dataset creation issue on the frontend

cypress/integration/datasets-attachment.spec.js
Fixing the status code after change in the backend: https://github.com/SciCatProject/scicat-backend-next/pull/354
=> fix the e2e tests after status code change in the backend

src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.html, src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts, src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.html, src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.ts, src/app/proposals/view-proposal-page/view-proposal-page.component.html, src/app/proposals/view-proposal-page/view-proposal-page.component.ts, src/assets/config.json
Few fixes:
1. fixed logbook data doesn't reload after first render. E.g., change tab causes logbook data missing.
2. fixed logbook not accessible from proposal page.
3. fixed logbook filter bar text search - when text search is empty nothing should happen. (previously, press Enter key on empty text search returns [Object Event])
4. fixed logbook router link is inactive when selecting filters.
As a user I want to see the logbook and use it without strange bugs!
router link inactive bug:
https://user-images.githubusercontent.com/78078898/225615465-51d99ff1-97d1-4e73-b8ab-c05895b01559.mp4
=> fix: make logbook accessible without much bugs

src/app/logbooks/logbooks-table/logbooks-table.component.html
logbook messages show display name
=> fix: logbook show display name

src/app/logbooks/logbooks-detail/logbooks-detail.component.html
[Short description of the pull request](fix: ogbook show display name 2)
* Items added
* changes made
=> fix: logbook show display name 2

cypress/integration/datasets-general.spec.js, cypress/support/commands.js, src/app/samples/sample-detail/sample-detail.component.html, src/app/samples/sample-detail/sample-detail.component.ts, src/app/shared/interceptors/snackbar.interceptor.ts, src/app/shared/modules/scientific-metadata/metadata-edit/metadata-edit.component.ts, src/app/shared/modules/scientific-metadata/metadata-view/metadata-view.component.ts, src/app/state-management/actions/samples.actions.ts, src/app/state-management/effects/samples.effects.spec.ts, src/app/state-management/effects/samples.effects.ts, src/app/state-management/reducers/samples.reducer.spec.ts, src/app/state-management/reducers/samples.reducer.ts, src/app/state-management/selectors/samples.selectors.spec.ts, src/app/state-management/selectors/samples.selectors.ts, src/app/state-management/state/samples.store.ts
- fix fetching sample by id instead of using findOne and separate call for fetching sample attachments
- fix sample attachments upload, remove and update
- add better error messages in notification
- fix sampleCharacteristics if all are removed
Samples needed some attention because most of the things were broken
* https://jira.esss.lu.se/browse/SWAP-3162
* https://jira.esss.lu.se/browse/SWAP-3176
* changes made
=> fix: fetch on sample shoud be findById and attachments should work

src/app/files/files-dashboard/files-dashboard.component.html, src/app/shared/modules/shared-table/shared-table.component.spec.ts, src/app/shared/modules/shared-table/shared-table.component.ts, src/app/shared/services/scicat-data-service.ts, src/app/shared/services/scicat.datasource.ts
Fetch data for files dashboard from new endpoint
Files page does not render data.
To
* changes made
=> fix: files page does not render data

CI/ESS/e2e/config.e2e.json, src/app/app-config.service.spec.ts, src/app/app-config.service.ts, src/app/datasets/batch-view/batch-view.component.ts, src/app/shared/interceptors/snackbar.interceptor.ts
=> feat: make snackbar notifications configurable

cypress/integration/datasets-attachment.spec.js, cypress/integration/datasets-general.spec.js, cypress/integration/datasets-keyword.spec.js, cypress/integration/datasets-metadata.spec.js, cypress/integration/datasets-public.spec.js, cypress/integration/datasets-publish.spec.js, cypress/integration/datasets-reduce.spec.js, cypress/support/commands.js
Improving the e2e tests because they started failing more often.
E2e tests failing randomly
=> fix: Improve e2e tests

CI/ESS/e2e/cypress.nestjs.json
=> fix: e2e tests on the backend use different config

src/app/datasets/dataset-detail/dataset-detail.component.ts, src/app/instruments/instrument-details/instrument-details.component.html, src/app/instruments/instrument-details/instrument-details.component.ts
Custom metadata edit button shouldn't shown to the user without permission
=> fix: allow only admin to edit custom metadata

src/app/files/files-dashboard/files-dashboard.component.html, src/app/jobs/jobs-dashboard-new/jobs-dashboard-new.component.html, src/app/proposals/proposal-dashboard/proposal-dashboard.component.html, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.html, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.spec.ts, src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts, src/app/shared/modules/shared-table/shared-table.component.html, src/app/shared/modules/shared-table/shared-table.component.scss, src/app/shared/modules/shared-table/shared-table.component.ts, src/app/shared/modules/shared-table/shared-table.module.ts, src/app/shared/services/scicat-data-service.ts, src/app/shared/services/scicat.datasource.ts
Use shared table for published data instead of another app table.
The motivation here is to move completely to the shared-table and not use any other table for data representation in the app.
* https://jira.esss.lu.se/browse/SWAP-3326
=> fix: Use of shared-table for published data representation

src/app/datasets/dataset-detail/dataset-detail.component.html, src/app/datasets/dataset-detail/dataset-detail.component.scss, src/app/datasets/dataset-detail/dataset-detail.component.ts
On dataset detail page
- removed instrument unique name 
- added copy success notification to pid copy to clipboard
=> fix: minor changes to UI in dataset detail page

.github/dependabot.yml
Group types and ngrx dependabot updates
=> Add dependabot group for types and ngrx

src/app/state-management/actions/user.actions.spec.ts, src/app/state-management/actions/user.actions.ts, src/app/state-management/effects/user.effects.spec.ts, src/app/state-management/effects/user.effects.ts, src/app/state-management/reducers/user.reducer.spec.ts
Redirect to the logoutURL if it is provided from the backend after user logs out.
=> fix: redirect to logoutURL if provided from the backend after logout

.github/workflows/test.yml, CI/ESS/e2e/docker-compose.e2e.yaml
Start docker-compose as real background service and add improved log output on failure
=> e2e improvement

src/app/state-management/reducers/instruments.reducer.spec.ts, src/app/state-management/reducers/instruments.reducer.ts, src/app/state-management/reducers/jobs.reducer.spec.ts, src/app/state-management/reducers/jobs.reducer.ts, src/app/state-management/reducers/policies.reducer.spec.ts, src/app/state-management/reducers/policies.reducer.ts, src/app/state-management/reducers/published-data.reducer.ts
fixed policy-delegate e2e test fail
=> fix: policy-delegate e2e test fail

.github/workflows/report-coverage.yml
See https://github.com/actions/github-script/issues/242
=> Update report-coverage.yml for new github api

cypress/e2e/other/samples-create.cy.js
=> Update samples-create.cy.js for new BE

src/app/datasets/dashboard/dashboard.component.html, src/app/datasets/dashboard/dashboard.component.scss, src/app/datasets/dashboard/dashboard.component.ts, src/app/datasets/datasets-filter/datasets-filter.component.html
Introduces full width text search bar on top of the main content widget in the dashboard. Essentially by moving corresponding component from the facets.
Resolves #1147
=> Full width search bar

.github/workflows/dependabot-auto-merge.yml
Refer to https://github.com/SciCatProject/scicat-backend-next/pull/1165
=> chore: improved dependabot-auto-merge

src/app/datasets/dashboard/dashboard.component.html, src/app/datasets/dashboard/dashboard.component.scss, src/app/datasets/dashboard/dashboard.component.ts, src/app/datasets/dashboard/full-text-search/full-text-search-bar.component.html, src/app/datasets/dashboard/full-text-search/full-text-search-bar.component.scss, src/app/datasets/dashboard/full-text-search/full-text-search-bar.component.ts, src/app/datasets/datasets.module.ts
=> Explicit search button

cypress/e2e/datasets/datasets-metadata.cy.js, src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts, src/app/datasets/jsonScientificMetadata/jsonScientificMetadata.component.html
added e2e test for https://github.com/SciCatProject/frontend/pull/1400
=> test: added e2e test for scientificMetadata json view table

.github/ISSUE_TEMPLATE/custom.md, .github/PULL_REQUEST_TEMPLATE.md
This PR implements the latest version of the templates used in github issues and PR
In the last developer meeting, it was discussed which documentation is required for each PR.
This PR implements the decision made in the meeting
* issue template file
* PR template file
=> Updated github issue and PR templates

src/app/users/user-settings/_user-settings-theme.scss, src/app/users/user-settings/user-settings.component.html, src/app/users/user-settings/user-settings.component.scss, src/app/users/user-settings/user-settings.component.ts
Enhanced user settings display and functionality with additional UI features and improvements.
To improve the user experience by adding a toggle button for viewing user access groups and updating the styles for better readability and interactivity.
- Added a toggle button to show/hide user access groups.
- Updated CSS for better styling of the toggle button and table layout.
- Included tooltips for the toggle button icons.
- Adjusted the max-width for inline elements in user settings.
* changes made
=> feat: added show more button for group list

.github/workflows/build-release.yml, .github/workflows/deploy.yml
Added Docker support for ARM64 for Github Actions.
ARM64 support
ARM64 support
.github/workflows/build-release.yml
.github/workflows/deploy.yml
=> fix: Added Support for Docker ARM

.github/workflows/report-coverage.yml
Fixed for Unhandled error: TypeError: Cannot read properties of undefined (reading 'downloadArtifact')
=> fix: fixed Comment on the pull request error

src/app/datasets/admin-tab/admin-tab.component.spec.ts, src/app/datasets/datasets-filter/settings/datasets-filter-settings.component.ts, src/app/shared/modules/filters/date-range-filter.component.ts, src/app/shared/modules/filters/group-filter.component.ts, src/app/shared/modules/filters/keyword-filter.component.ts, src/app/shared/modules/filters/location-filter.component.ts, src/app/shared/modules/filters/pid-filter-contains.component.ts, src/app/shared/modules/filters/pid-filter-startsWith.component.ts, src/app/shared/modules/filters/pid-filter.component.ts, src/app/shared/modules/filters/text-filter.component.ts, src/app/shared/modules/filters/type-filter.component.ts
Avoid using `this.constructor.name` to resolve filter label
=> Resolve #1570

src/app/datasets/dataset-table/dataset-table.component.html, src/app/state-management/effects/datasets.effects.ts, src/app/users/user-settings/user-settings.component.scss
- fixed public / my data view buttons not working on the dataset table
- fixed sorting button not working on the dataset table
- fixed metadataKeys endpoint returning empty value
Final improvement before new release.
Please provide a list of the fixes implemented in this PR
* Items added
Please provide a list of the changes implemented by this PR
* changes made
=> fix: fixed issues with public/my data view buttons, sorting, and metadataKeys list on dataset table

package-lock.json
This PR fixes the Snyk vulnerability check failure caused by the tmp dependency version <0.2.4 from exceljs.
Please provide a list of the fixes implemented in this PR
* Items added
Please provide a list of the changes implemented by this PR
* changes made
=> chore: fix snyk vulnerability check

Dockerfile
Added comment about port change
Added correct breaking change title to bump major release version update
Please provide a list of the fixes implemented in this PR
* Items added
Please provide a list of the changes implemented by this PR
* changes made
=> BREAKING CHANGE(docker): update note about frontend port change to 8080
